framework:
  workflows:
    ticketTraitement:
      type: "workflow" # or 'state_machine'
      audit_trail:
        enabled: true
      marking_store:
        type: "method"
        property: "currentPlace"
      supports:
        - App\Entity\Ticket
      initial_marking: initial
      places:
        - initial
        - wip
        - clientAcceptance
        - techConfirmation
        - finished
      transitions:
        to_wip:
          from: initial
          to: wip
        to_client:
          from: wip
          to: clientAcceptance
        to_tech:
          from: clientAcceptance
          to: techConfirmation
        to_finished:
          from: [clientAcceptance, techConfirmation]
          to: finished
