framework:
  workflows:
    ticketTraitement:
      type: "state_machine" # or 'state_machine'
      audit_trail:
        enabled: true
      marking_store:
        type: "method"
        property: "ticketStatut"
      supports:
        - App\Entity\Ticket
      initial_marking: initial
      places:
        - initial
        - wip
        - clientAcceptance
        - finished
      transitions:
        to_wip:
          from: initial
          to: wip
        to_client:
          from: wip
          to: clientAcceptance
        to_finished:
          from: [wip, clientAcceptance]
          to: finished
